apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: foonction-controller
  namespace: mc-controllers
spec:
  generateSelector: true
  parentResource:
    apiVersion: apigee.google.com/v1
    resource: foonctions
  childResources:
  - apiVersion: apps/v1
    resource: deployments
  - apiVersion: v1
    resource: services
  - apiVersion: networking.istio.io/v1alpha3
    resource: virtualservices
  hooks:
    sync:
      webhook:
        url: http://apigee-controller.metacontroller/foonction-controller-sync
    finalize:
      webhook:
        url: http://apigee-controller.metacontroller/foonction-controller-sync
