apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: foo
spec:
  selector:
    matchLabels:
      app: foo
      version: foo
  template:
    metadata:
      labels:
        app: foo
        version: foo
        managed-by: apigee
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: foonction
        image: foo
        ports:
        - containerPort: foo
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep 3000"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep 3000"
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongoauth
                key: user
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
