apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foonctions.apigee.google.com
spec:
  group: apigee.google.com
  version: v1
  scope: Namespaced
  names:
    plural: foonctions
    singular: foonction
    kind: foonction
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["name","version","registryUrl","gateway","virtualService","trigger"]
          properties:
            name:
              type: "string"
              minimum: 1
            version:
              type: "string"
              minimum: 1
            registryUrl:
              type: "string"
              minimum: 1
            gateway:
              type: "string"
              minimum: 1
            virtualService:
              type: "string"
              minimum: 1
            trigger:
              type: "string"
              minimum: 1
            prefix:
              type: "string"
              minimum: 1
